#!/usr/bin/env bash
set -e

OS=$1

if type -p gcloud; then
	exit 0
fi
case "$OS" in
	linux)
		# Create an environment variable for the correct distribution
		export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
		# Add the Cloud SDK distribution URI as a package source
		echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
		# Import the Google Cloud Platform public key
		curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
		# Update the package list and install the Cloud SDK
		sudo apt-get -qq update && sudo apt-get -qq install google-cloud-sdk
		;;

	*)
		if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then
			rm -rf $HOME/google-cloud-sdk;
			export CLOUDSDK_CORE_DISABLE_PROMPTS=1;
			curl -s https://sdk.cloud.google.com | bash;
		fi
		export PATH=~/google-cloud-sdk/bin:$PATH
		;;
esac
