#!/usr/bin/env bash
set -e

OS=$1

if type -p torsocks; then
	exit 0
fi
case "$OS" in
	osx)
		brew install torsocks
		;;
	linux)
		cd /tmp
		wget https://github.com/dgoulet/torsocks/archive/v2.1.0.tar.gz
		tar xvfz v2.1.0.tar.gz
		cd torsocks-2.1.0
		./autogen.sh
		./configure --prefix=/usr
		make
		sudo make install
		;;
esac
