#!/usr/bin/env bash
set -e

OS=$1

if type -p kubectl; then
	exit 0
fi

# https://kubernetes.io/docs/tasks/tools/install-kubectl/

# Wish there were packages... There don't seem to be any dpkgs for Ubuntu
# and Homebrew only has the newest version, too new for us to actually use
# (due to the version of the testing cluster).
VER="v1.6.13"
BASE="https://storage.googleapis.com/kubernetes-release/release/"

case "$OS" in
	linux)
		curl -LO ${BASE}${VER}/bin/linux/amd64/kubectl
		chmod +x ./kubectl
		;;

	osx)
		curl -LO ${BASE}${VER}/bin/darwin/amd64/kubectl
		chmod +x ./kubectl
		;;

	*)
		echo "Unknown platform."
		exit 1
		;;
esac
